default_ethereum_client_images:
### Consensus layer clients
  lighthouse: ethpandaops/lighthouse:unstable-8cf686f
  lodestar: ethpandaops/lodestar:peerDAS-513bccc
  nimbus: ethpandaops/nimbus-eth2:pdsync-e085909
  prysm: ethpandaops/prysm-beacon-chain:peerDAS-ae626d5
  prysm_validator: ethpandaops/prysm-validator:peerDAS-ae626d5
  teku: ethpandaops/teku:nashatyrev-das-cefa2c5
  grandine: ethpandaops/grandine:hangleang-feature-das-7ee46ff
### Execution layer clients
  besu: hyperledger/besu:latest
  geth: ethereum/client-go:stable
  erigon: thorax/erigon:devel
  ethereumjs: ethpandaops/ethereumjs:master
  nethermind: nethermindeth/nethermind:master
  reth: ethpandaops/reth:main


default_tooling_images:
  xatu_sentry: ethpandaops/xatu:latest
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: ethpandaops/tx-fuzz:latest
  forkmon: skylenet/nodemonitor:darkmode
  forky: ethpandaops/forky:latest
  fauceth: skylenet/fauceth:fix_fee_estimation
  powfaucet: pk910/powfaucet:v2-stable
  ethstats: skylenet/ethstats-server:poa-no-geoip
  homepage: ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: ethpandaops/checkpointz:latest
  blockscout: blockscout/blockscout:master
  beacon_metrics_gazer: dapplion/beacon-metrics-gazer:latest
  eth_fauceth: chainflag/eth-faucet:latest
  blobscan: blossomlabs/blobscan:latest
  blobscan_indexer: blossomlabs/blobscan-indexer:latest
  dora: ethpandaops/dora:master-latest
  dugtrio: ethpandaops/dugtrio:latest
  ethereum_genesis_generator: ethpandaops/ethereum-genesis-generator:3.3.7
  tracoor: ethpandaops/tracoor:0.0.25-debian
  ncli: status-im/nimbus-eth2:unstable
  lcli: ethpandaops/lighthouse:unstable-a94b12blo
  zcli: electra
  assertoor: ethpandaops/assertoor:electra-support-latest

