prysm_container_command_extra_simple_args:
  - --grpc-gateway-corsdomain=*
  - --chain-config-file=/network-config/config.yaml
  - --genesis-state=/network-config/genesis.ssz
  - --contract-deployment-block={{ ethereum_network_deposit_contract_block }}
  - --min-sync-peers=1
  - --pprof
  - --enable-debug-rpc-endpoints
  - --verbosity=debug
  - --subscribe-all-subnets
  - --data-columns-withhold-count=16